deploymentName: orders-deployment
serviceName: orders
appLabel: orders
appName: orders

replicaCount: 1

image:
  repository: kanaparthiphani/orderservice
  tag: v3

containerPort: 8086

service:
  type: ClusterIP
  port: 8086
  targetPort: 8086

appname_enabled: false
profile_enabled: true
config_enabled: true
eureka_enabled: true
resouceserver_enabled: true
otel_enabled: true
kafka_enabled: true